name: Build Game
on: push

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: "Collector: The Berserkening"

permissions:
  contents: write

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/"${GODOT_VERSION}".stable ~/.local/share/godot/export_templates/"${GODOT_VERSION}".stable

          ls -alh ~/.local/share/godot/export_templates/

      - name: Build
        run: |
          mkdir -v -p build/web
          godot -v --headless --rendering-driver opengl3 --export-release "Web" build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web

  publish-changes:
    name: Publish changes
    runs-on: ubuntu-latest
    needs:
      - export-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Load artifact
        uses: actions/download-artifact@v1
        with:
          name: web

      - name: Commit changes
        run: |
          git config --global user.name "stringybot"
          git config --global user.email "stringybot@ci"
          git add .
          git commit -m 'published new build!'
          git push
